# Generated by Django 4.1.3 on 2022-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("members", models.CharField(max_length=140)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
            ],
        ),
    ]
